databases:
  - name: teamup-db
    databaseName: teamup
    user: teamup
    plan: free

services:
  - type: web
    name: teamup
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: teamup-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
